### ISSUE TITLE
Create a CircleCI job to synchronize code from staging to production

### ISSUE THREAD

**Issue by mgwalker** [CMSgov/CMCS-DSG-DSS-Certification-Staging#81]
## What is the goal or purpose of this issue?

The staging and production repos are not forks, so GitHub isn't "tracking" them. In order to keep changes in the staging repo synchronized to production, a CircleCI job will kick off whenever a change is pushed to the `main` branch of the staging repo.

The CircleCI job will:
- clone the staging repo
- checkout the `main` branch
- push to the `main` branch of the production repo

The CirleCI job will need to be configured with a GitHub token with write permissions to the production repo. The staging repo is public and only needs to be read, so no staging tokens are necessary.

## This issue is resolved when...
- [x] a CircleCI project exists for the staging repo
- [ ] the staging repo has a non-main build branch
- [ ] a CircleCI build is initiated whenever a change is pushed to the `main` branch of the staging repo
- [ ] the CircleCI build successfully pushes the changes in the staging repo into the main repo

## Additional context
- **This issue is blocked until the staging repo is created**

**Comment by sknep** [comment]
@mgwalker Hey Greg! I've been picked to help out on a few issues here through a recent microrequest. I've not used CircleCI before but am super interested in learning it. Any chance we could pair or coordinate a bit on this one?

**Comment by mgwalker** [comment]
You bet! I haven't done anything with CircleCI in a while either, so it'll be fun to remember how it works.

**Comment by sknep** [comment]
I started looking into this but it seems I don't have the adequate tier of access in order to continue: 
![Screen Shot 2021-11-30 at 10 53 55 AM](https://user-images.githubusercontent.com/4451344/144091882-c3c08d78-22a3-456f-9cc5-6617fec55517.png)

@NAretakis if you could elevate my (and possibly Greg's?) GitHub account access, I might be able to take a closer look.

**Comment by sknep** [comment]
something like...

```
version: 2.1

jobs:
  deploy-prod-from-main:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Add deployment key fingerprint from prod repo for CircleCI to use for a push at https://github.com/CMSgov/MESCertificationRepo/settings/keys
      - add_ssh_keys:
          fingerprints:
            - "XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"
      # update this line when the repo is renamed
      - run: git remote add prod_repo git@github.com:CMSgov/MESCertificationRepo.git
      - run:
          name: "Updating prod"
          command: "git push prod_repo main:main"

workflows:
  # Workflow to deploy staging repo changes to prod on changes to main
  deploy-prod-workflow:
    jobs:
      - deploy-prod-from-main:
          filters:
            branches:
              only:
                - main
```

but we need to generate the deploy key and I don't have access to  https://github.com/CMSgov/MESCertificationRepo/settings/keys
